### ISSUE TITLE
Allow replace cloud-init ssh with "accessCredentials"

### ISSUE THREAD

**Issue by jseguillon** [ansible-community/molecule-kubevirt#12]
Spotted this incredible feature during Kubevirt Summit : https://github.com/kubevirt/kubevirt/pull/4195 

```
  accessCredentials:
  - sshPublicKey:
      source:
        secret:
          secretName: my-pub-key
      propagationMethod:
        qemuGuestAgent:
          users:
          - "fedora"
```

Using this would let users fully customize cloud-init but still ensure molecule user can get credentials.
